name: $(Build.BuildId)
queue:
  name: API Enablement
  demands: OS -equals Linux
trigger:
- master
steps:
- bash: |
   export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
   chmod +x ./pipeline.sh
   ./pipeline.sh $(Build.BuildId)
  displayName: Pipeline Bash Script
  enabled: false

- powershell: |
   $env:AWS_SECRET_ACCESS_KEY = "$(AWS_SECRET_ACCESS_KEY)"
   ./pipeline.ps1 -pushImage -buildNumber $(Build.BuildId)
  displayName: Pipeline PowerShell Script
  enabled: true

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: testresult.trx
    searchFolder: '$(System.DefaultWorkingDirectory)/src'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: manifests"
  inputs:
    PathtoPublish: k8s
    ArtifactName: manifests

